package bplus

// Entry is one leaf entry of the B+ tree. Key is always the order-preserving
// binary representation generated by storage.EncodeKey/Table.EncodeKey.
type Entry[V comparable] struct {
	Key   []byte
	Value V
}

func cloneKey(k []byte) []byte { return append([]byte(nil), k...) }
